In [1]:
#pip install numpy
import numpy as np

In [2]:
lista= [1,2,3]

In [3]:
lista

[1, 2, 3]

In [4]:
np.array(lista)

array([1, 2, 3])

In [5]:
matriz=[[1,2,3],[4,5,6]]

In [6]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
arr=np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.random.rand(5)

array([0.82772238, 0.67723147, 0.03701708, 0.23922997, 0.90087369])

In [29]:
np.random.rand(5)*100

array([46.60695943, 89.73866127, 46.47491624, 59.51316179, 38.09197445])

In [32]:
np.random.randint(0,100,10)

array([55, 87, 59,  3, 13, 47,  2, 16, 15, 52])

## aula indexação e fatiamento de arrays


In [35]:
arr = np.arange(0,30,3)

In [39]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [43]:
arr[3]

9

In [45]:
arr[2:5]

array([ 6,  9, 12])

In [47]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [49]:
arr[3:]

array([ 9, 12, 15, 18, 21, 24, 27])

In [53]:
arr=np.arange(50).reshape((5,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr.shape

(5, 10)

In [57]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
arr2=arr[:3]

In [61]:
arr2[:]=100
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [63]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [77]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [81]:
bol=arr>=50

In [83]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [5]:
import numpy as np

In [7]:
arr=np.arange(0,16)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [13]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [15]:
arr/arr

C:\Users\jpedr\AppData\Local\Temp\ipykernel_18524\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [17]:
 arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [19]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [21]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [27]:
np.mean(arr)

7.5

In [29]:
np.max(arr)

15

In [31]:
np.min(arr)

0

In [35]:
arr.min()

0